/*
  Initial data model design for Anapath backend (PostgreSQL-ready)

  1) laboratories
  - id (PK)
  - name
  - address
  - phone
  - created_at

  2) users
  - id (PK)
  - laboratory_id (FK -> laboratories.id)
  - email (unique)
  - password_hash
  - role
  - created_at

  3) patients
  - id (PK)
  - laboratory_id (FK -> laboratories.id)
  - first_name
  - last_name
  - age
  - sex
  - phone
  - general_history
  - created_at

  4) exams
  - id (PK)
  - laboratory_id (FK -> laboratories.id)
  - patient_id (FK -> patients.id)
  - exam_number (generated by backend)
  - exam_type (cytology | histology)
  - clinic_name
  - requesting_doctor
  - requested_date
  - registered_date
  - result_issued_date
  - sample_nature
  - exam_history
  - diagnosis_keywords
  - status
  - created_at

  5) reports
  - id (PK)
  - exam_id (FK -> exams.id, unique)
  - clinical_info
  - macroscopy
  - microscopy
  - conclusion
  - created_at
  - updated_at

  Relations:
  - One laboratory has many users, patients, exams.
  - One patient has many exams.
  - One exam belongs to one patient.
  - One exam has one report.
*/

export const models = {
  laboratories: 'planned',
  users: 'planned',
  patients: 'planned',
  exams: 'planned',
  reports: 'planned',
};
